### ISSUE TITLE
where is the part of "PruMerge"?

### ISSUE THREAD

**Issue by muyu42** [42Shawn/LLaVA-PruMerge#1]
In fact, I went through the entire repository and couldn't find this part of the code, and the inferred scripts in the readme didn't work because some data or files were missing

**Comment by mu-cai** [comment]
Hi,

The core of our prumerge is here: https://github.com/42Shawn/LLaVA-PruMerge/blob/main/llava/model/multimodal_encoder/clip_encoder.py#L85

Please have a look!
