### ISSUE TITLE
Question about finetuning process

### ISSUE THREAD

**Issue by ZiangWu-77** [42Shawn/LLaVA-PruMerge#8]
Good work actually.
I am replicating your work and wondering which dataset was used when you finetune the prumerge and prumerge+?
Eager for your answer.

**Comment by niiickZ** [comment]
I have the same question. And I'm also curious about details of finetuning hyperparamters.

**Comment by 42Shawn** [comment]
Basically, I have used the same finetuning setting inherited from the LLaVA, including the finetuning hyperparamters and datasets. For more training details, please refer to the original llava project.

**Comment by ZiangWu-77** [comment]
> Basically, I have used the same finetuning setting inherited from the LLaVA, including the finetuning hyperparamters and datasets. For more training details, please refer to the original llava project.

Reger that. Thanks for your reply.
